// Following links from inside the editor — the Notion click gesture.
//
// Why this needs a plugin at all: the document surface is `contenteditable`,
// and browsers deliberately do NOT follow links there — a click places the
// caret so the text stays editable. Crepe ships link chrome (the hover tooltip
// with copy / edit / remove), but nothing that *follows* a link, so before
// this a link in a note was decoration: clickable-looking, inert.
//
// Notion's model, which this mirrors:
//
//   - A plain left click follows the link. External URLs leave for the system
//     browser; an internal (in-workspace) target opens in the app.
//   - Hovering shows the link's own chrome, so editing a link never requires
//     opening it first (Crepe's tooltip already does this half).
//   - A modifier-click, a drag, or a double click is NOT a follow: it falls
//     through to normal caret/selection behavior. That's the escape hatch for
//     getting the caret *into* link text — same as arrowing in.
//
// Where a followed link goes is the host's business (the desktop app opens the
// browser or another tab; a host-less mount opens a browser tab), so
// this plugin only decides *whether* a click is a follow and hands the raw
// href out. One exception stays here: an in-document `#anchor` never leaves
// the editor — it scrolls to its heading, like Notion jumping to a block.

import { $prose } from "@milkdown/kit/utils";
import { Plugin, PluginKey } from "@milkdown/kit/prose/state";
import type { EditorView } from "@milkdown/kit/prose/view";

// What the host does with a followed link. The href is passed through
// verbatim — exactly what the markdown says — so the host can tell an external
// URL from a path to a note next door.
export type LinkOpener = (href: string) => void;

export const linkOpenKey = new PluginKey("doklin-link-open");

// Schemes a link in a note may hand to a browser. Anything else — javascript:,
// data:, a custom app scheme — is dropped: notes travel (published pages,
// synced workspaces, shared folders), so a link in one is not automatically
// something the reader asked to run. A schemeless href (a path, an anchor) is
// not a scheme and passes.
const SCHEME_RE = /^[a-z][a-z0-9+.-]*:/i;
const WEB_SCHEME_RE = /^(https?:|mailto:)/i;

/**
 * The plain host behavior: open the link in a browser tab, letting the browser
 * resolve a relative href against the current page. What the published web
 * shell wants, and what the editor falls back to when a host doesn't say.
 */
export const openInBrowserTab: LinkOpener = (href) => {
  if (SCHEME_RE.test(href) && !WEB_SCHEME_RE.test(href)) return;
  window.open(href, "_blank", "noopener");
};

// A press that travelled further than this was a drag (selecting text), not a
// click on a link.
const DRAG_SLOP = 4;

// Milkdown gives every heading an id (lowercased text, spaces to dashes) and
// renders it on the DOM node. Anchors written by hand — or generated by
// another tool — tend to be GitHub-style slugs instead, which also drop
// punctuation, so match on both spellings.
const slug = (s: string) =>
  s
    .toLowerCase()
    .trim()
    .replace(/[^\p{L}\p{N}\s-]/gu, "")
    .replace(/\s+/g, "-");

// Scroll to the heading a `#fragment` names. Deliberately does not touch the
// selection: jumping to a section shouldn't move the caret out from under the
// user (same reason Editor.tsx scrolls search hits by DOM).
function scrollToAnchor(view: EditorView, fragment: string): boolean {
  let want = fragment;
  try {
    want = decodeURIComponent(fragment);
  } catch {
    // a malformed escape sequence — match the raw text instead
  }
  const headings = view.dom.querySelectorAll<HTMLElement>("h1, h2, h3, h4, h5, h6");
  for (const h of headings) {
    if (h.id === want || slug(h.textContent ?? "") === slug(want)) {
      h.scrollIntoView({ block: "start", behavior: "smooth" });
      return true;
    }
  }
  return false;
}

/**
 * Click-to-follow for links in the editor. `getOpener` is read per click so
 * the host can swap its handler (or drop it) without remounting the editor.
 */
export function linkOpenPlugin(getOpener: () => LinkOpener | undefined) {
  return $prose(() => {
    let downX = Number.NaN;
    let downY = Number.NaN;

    // A follow is a deliberate, unmodified, stationary left click. Everything
    // else — modifier held, dragged, double click — is the user working with
    // the *text*, and gets the editor's normal behavior.
    const isFollow = (e: MouseEvent) =>
      e.button === 0 &&
      e.detail === 1 &&
      !e.metaKey &&
      !e.ctrlKey &&
      !e.altKey &&
      !e.shiftKey &&
      Math.abs(e.clientX - downX) <= DRAG_SLOP &&
      Math.abs(e.clientY - downY) <= DRAG_SLOP;

    const follow = (view: EditorView, href: string) => {
      if (!href) return;
      if (href.startsWith("#")) {
        scrollToAnchor(view, href.slice(1));
        return;
      }
      getOpener()?.(href);
    };

    return new Plugin({
      key: linkOpenKey,
      props: {
        handleDOMEvents: {
          mousedown: (_view, event) => {
            downX = event.clientX;
            downY = event.clientY;
            return false;
          },
          click: (view, event) => {
            const target = event.target as HTMLElement | null;
            const anchor = target?.closest?.("a[href]");
            if (!anchor || !view.dom.contains(anchor)) return false;
            // Whatever happens next, the webview must not navigate: in the
            // desktop app that would replace Doklin itself with the site.
            event.preventDefault();
            if (!isFollow(event)) return false; // caret/selection, not a follow
            follow(view, anchor.getAttribute("href") ?? "");
            return true;
          },
        },
      },
      view: (view) => {
        // Crepe's hover tooltip renders the URL as a real <a target="_blank">
        // mounted NEXT TO the editor (view.dom.parentElement), where
        // ProseMirror's own handlers never see it. Clicking it reads as
        // "open this" and would otherwise navigate the webview, so route it
        // through the same follow path — no drag/modifier rules, it's chrome.
        const host = view.dom.parentElement;
        const onChromeClick = (event: MouseEvent) => {
          const anchor = (event.target as HTMLElement | null)?.closest?.("a[href]");
          if (!anchor || view.dom.contains(anchor)) return; // in-document: handled above
          event.preventDefault();
          if (event.button !== 0) return;
          follow(view, anchor.getAttribute("href") ?? "");
        };
        host?.addEventListener("click", onChromeClick);
        return {
          destroy: () => host?.removeEventListener("click", onChromeClick),
        };
      },
    });
  });
}
